# fly.toml app configuration file generated for baechat on 2023-06-16T22:29:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "baechat"
primary_region = "nrt"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
